package ex201;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

public class VelocityDlg extends javax.swing.JDialog {

    private boolean ok;
    private static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    private static final DateTimeFormatter dt = DateTimeFormatter.ofPattern("HH:mm");

    public VelocityDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setTitle("Eingabedialog");
        ok = false;

        tf_Date.setText(LocalDate.now().format(dtf));
        tf_Time.setText(LocalTime.now().format(dt));
    }

    public boolean isOk() {
        return ok;
    }

    public Measurement getData() {
        String kennzeichen = "";
        int vGem = 0;
        int vErl = 0;

        if (tf_Kennzeichen.getText() != "") {
            kennzeichen = tf_Kennzeichen.getText().toUpperCase();
        } else {
            JOptionPane.showMessageDialog(null, "Bitte ein vernünftiges Kennzeichen eingeben!", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        try {
            vGem = Integer.parseInt(tf_Vgem.getText());
            vErl = Integer.parseInt(tf_Verl.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Bitte vernünftige Werte eingeben!", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        int ueberschreitung = 0;

        if ((vGem - vErl) > 0) {
            ueberschreitung = vGem - vErl;
        }

        Measurement measure = new Measurement(LocalDate.parse(tf_Date.getText(), dtf), LocalTime.parse(tf_Time.getText()), kennzeichen, vErl, vGem, ueberschreitung);
        return measure;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_Date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_Time = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_Kennzeichen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_Vgem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_Verl = new javax.swing.JTextField();
        bt_Ok = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Datum:");
        jPanel1.add(jLabel1);

        tf_Date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Date);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Uhrzeit:");
        jPanel1.add(jLabel2);

        tf_Time.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_Time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Time);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Kennzeichen:");
        jPanel1.add(jLabel5);

        tf_Kennzeichen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_Kennzeichen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Kennzeichen);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("V-Gemessen:");
        jPanel1.add(jLabel4);

        tf_Vgem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_Vgem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Vgem);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("V-Erlaubt:");
        jPanel1.add(jLabel3);

        tf_Verl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_Verl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Verl);

        bt_Ok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_Ok.setText("Übernehmen");
        bt_Ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onOk(evt);
            }
        });
        jPanel1.add(bt_Ok);

        bt_Cancel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_Cancel.setText("Abbrechen");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onCancel(evt);
            }
        });
        jPanel1.add(bt_Cancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onOk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOk
        ok = true;
        this.setVisible(false);
    }//GEN-LAST:event_onOk

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        ok = false;
        this.setVisible(false);
    }//GEN-LAST:event_onCancel

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VelocityDlg dialog = new VelocityDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_Date;
    private javax.swing.JTextField tf_Kennzeichen;
    private javax.swing.JTextField tf_Time;
    private javax.swing.JTextField tf_Verl;
    private javax.swing.JTextField tf_Vgem;
    // End of variables declaration//GEN-END:variables
}
